export { Heading } from './Heading';
export type { HeadingProps } from './Heading';
export { Subheading } from './Subheading';
export type { SubheadingProps } from './Subheading';
export { Body } from './Body';
export type { BodyProps } from './Body';
export { Caption } from './Caption';
export type { CaptionProps } from './Caption';
export { Label } from './Label';
export type { LabelProps } from './Label';
export { Quote } from './Quote';
export type { QuoteProps } from './Quote';
export { CodeBlock } from './CodeBlock';
export type { CodeBlockProps } from './CodeBlock';
